spring:
  application:
    name: spring_boot_shopDEV
  datasource:
    url: jdbc:mysql://localhost:8811/shopDEVJava
    username: root
    password: dinhpham
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true